#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawn } from "node:child_process";

import "dotenv/config";
import openapiTS, { astToString } from "openapi-typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = path.resolve(__dirname, "../src/types/blurfield-api.d.ts");
const CLIENT_PATH = path.resolve(__dirname, "../src/lib/client.ts")
const INDEX_FILE_PATH = path.resolve(__dirname, "../src/index.ts")
function buildProject(){
  const build = spawn("pnpm", ["run", "build"], {
  stdio: "inherit",
  shell: true,
});

build.on("close", (code) => {
  if (code === 0) {
    console.log("Build completed successfully.");
  } else {
    console.error(`Build failed with exit code ${code}`);
    process.exitCode = code;
  }
});
}

const INDEX_FILE_CONTENT = `
/**
* This file is auto-generated by scripts/sync-api.ts
* Do not edit manually. Run \`npm run sync-api\` to regenerate.
*
* Generated at: ${new Date().toISOString()}
*/
export * from './lib/client.js'
export * from './types/blurfield-api.js'
`
async function main() {
  const args = process.argv
  const urlIndex = args.findIndex((arg)=>arg==="-url")
  const apiUrl = process.env.BACKEND_API_URL|| args[urlIndex+1];
  
  if (!apiUrl) {
    console.error("Error: BACKEND_API_URL environment variable is required");
    process.exit(1);
  }
  const CLIENT_CONTENT=`
/**
* This file is auto-generated by scripts/sync-api.ts
* Do not edit manually. Run \`npm run sync-api\` to regenerate.
*
* Generated at: ${new Date().toISOString()}
*/
import createClient, { ClientOptions } from 'openapi-fetch'
import {paths} from '../types/blurfield-api.js'
export const createAuthClient = (clientOptions:ClientOptions)=>{
    return createClient<paths>(clientOptions)
}
`
  const openApiUrl = `${apiUrl}/docs-json`;
  console.log(`Fetching OpenAPI spec from: ${openApiUrl}`);

  const ast = await openapiTS(new URL(openApiUrl));
  const contents = astToString(ast);

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_PATH);
  const clientOutputDir = path.dirname(CLIENT_PATH)
    const indexoutputdir = path.dirname(INDEX_FILE_PATH)

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  if(!fs.existsSync(clientOutputDir)){
    fs.mkdirSync(clientOutputDir,{recursive:true})
  }

    if(!fs.existsSync(indexoutputdir)){
    fs.mkdirSync(indexoutputdir,{recursive:true})
  }

  // Add header comment
  const header = `/**
* This file is auto-generated by scripts/sync-api.ts
* Do not edit manually. Run \`npm run sync-api\` to regenerate.
*
* Generated from: ${openApiUrl}
* Generated at: ${new Date().toISOString()}
*/
  `;

  fs.writeFileSync(OUTPUT_PATH, header + contents);
  console.log(`Types written to: ${OUTPUT_PATH}`);
  fs.writeFileSync(CLIENT_PATH,CLIENT_CONTENT)
  console.log(`Client  written to: ${CLIENT_PATH}`);
    fs.writeFileSync(INDEX_FILE_PATH,INDEX_FILE_CONTENT)
  console.log(`Index  written to: ${INDEX_FILE_PATH}`);
  console.log("\n \n\ \n================================================================")
  console.debug("compiling all files")
  buildProject()
  console.log("================================================================")
  

}


console.log(`
▗▖ ▗▖▗▖  ▗▄▄▄▖▗▄▄▄▖▗▖  ▗▖ ▗▄▖▗▄▄▄▖▗▄▄▄▖     ▗▄▖ ▗▖ ▗▖▗▄▄▄▖▗▖ ▗▖  █
▐▌ ▐▌▐▌    █    █  ▐▛▚▞▜▌▐▌ ▐▌ █  ▐▌       ▐▌ ▐▌▐▌ ▐▌  █  ▐▌ ▐▌  █
▐▌ ▐▌▐▌    █    █  ▐▌  ▐▌▐▛▀▜▌ █  ▐▛▀▀▘    ▐▛▀▜▌▐▌ ▐▌  █  ▐▛▀▜▌  █
▝▚▄▞▘▐▙▄▄▖ █  ▗▄█▄▖▐▌  ▐▌▐▌ ▐▌ █  ▐▙▄▄▖    ▐▌ ▐▌▝▚▄▞▘  █  ▐▌ ▐▌ ▄▄▄▖
                                                              
                                                              
                                                                                                                                              
  \n
  `)
main().catch((err) => {
  console.error("Failed to sync API types:", err);
  process.exit(1);
});