
/**
* This file is auto-generated by scripts/sync-api.ts
* Do not edit manually. Run `npm run sync-api` to regenerate.
*
* Generated at: 2026-08-16T18:35:28.538Z
*/
import createClient, { ClientOptions } from 'openapi-fetch'
import {paths} from '../types/blurfield-api.js'
export const createAuthClient = (clientOptions:ClientOptions)=>{
    return createClient<paths>(clientOptions)
}
