#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawn } from "node:child_process";
import dotenv from "dotenv";
import openapiTS, { astToString } from "openapi-typescript";
dotenv.config()
function getPackageManager() {
  const cwd = process.cwd();

  if (fs.existsSync(path.join(cwd, "pnpm-lock.yaml"))) {
    return "pnpm";
  }

  if (fs.existsSync(path.join(cwd, "yarn.lock"))) {
    return "yarn";
  }

  if (fs.existsSync(path.join(cwd, "bun.lockb")) ||
      fs.existsSync(path.join(cwd, "bun.lock"))) {
    return "bun";
  }

  return "npm";
}
function installDependencies() {
  const manager = getPackageManager();

  const commands = {
    pnpm: ["add", "openapi-fetch"],
    npm: ["install", "openapi-fetch"],
    yarn: ["add", "openapi-fetch"],
    bun: ["add", "openapi-fetch"],
  };

  return new Promise((resolve, reject) => {
    const install = spawn(
      manager,
      commands[manager],
      {
        cwd: process.cwd(),
        stdio: "inherit",
      }
    );

    install.on("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`${manager} install failed with code ${code}`));
    });
  });
}
const currentDir = process.cwd()
const OUTPUT_PATH = path.join(
 currentDir,
  "/src/types/ultimate-auth-api.d.ts"
);

const CLIENT_PATH = path.join(
 currentDir,
  "/src/lib/ultimate-auth/client.ts"
);




async function main() {
  const args = process.argv
  const urlIndex = args.findIndex((arg)=>arg==="-url")
  const apiUrl = process.env.AUTH_API|| args[urlIndex+1];
  
  if (!apiUrl) {
    console.error("Error: BACKEND_API_URL environment variable is required");
    process.exit(1);
  }
  const CLIENT_CONTENT=`
/**
* This file is auto-generated by scripts/sync-api.ts
* Do not edit manually. Run \`npm run sync-api\` to regenerate.
*
* Generated at: ${new Date().toISOString()}
*/
import createClient, { ClientOptions } from 'openapi-fetch'
import {paths} from '../../types/ultimate-auth-api.js'
export const createAuthClient = (clientOptions:ClientOptions)=>{
    return createClient<paths>(clientOptions)
}
  export const authClient = createAuthClient({baseUrl:process.env.AUTH_API})

`
  const openApiUrl = `${apiUrl}/docs-json`;
  console.log(`Fetching OpenAPI spec from: ${openApiUrl}`);

  const ast = await openapiTS(new URL(openApiUrl));
  const contents = astToString(ast);

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_PATH);
  const clientOutputDir = path.dirname(CLIENT_PATH)

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  if(!fs.existsSync(clientOutputDir)){
    fs.mkdirSync(clientOutputDir,{recursive:true})
  }


  // Add header comment
  const header = `/**
* This file is auto-generated by scripts/sync-api.ts
* Do not edit manually. Run \`npm run sync-api\` to regenerate.
*
* Generated from: ${openApiUrl}
* Generated at: ${new Date().toISOString()}
*/
  `;

  fs.writeFileSync(OUTPUT_PATH, header + contents);
  console.log(`Types written to: ${OUTPUT_PATH}`);
  fs.writeFileSync(CLIENT_PATH,CLIENT_CONTENT)
  console.log(`Client  written to: ${CLIENT_PATH}`);
  console.log("\n \n\ \n================================================================")
  console.log("Installing dependencies...")
  await installDependencies()
  console.log("Installed dependencies")
  console.log("================================================================")
  

}


console.log(`
▗▖ ▗▖▗▖  ▗▄▄▄▖▗▄▄▄▖▗▖  ▗▖ ▗▄▖▗▄▄▄▖▗▄▄▄▖     ▗▄▖ ▗▖ ▗▖▗▄▄▄▖▗▖ ▗▖  █
▐▌ ▐▌▐▌    █    █  ▐▛▚▞▜▌▐▌ ▐▌ █  ▐▌       ▐▌ ▐▌▐▌ ▐▌  █  ▐▌ ▐▌  █
▐▌ ▐▌▐▌    █    █  ▐▌  ▐▌▐▛▀▜▌ █  ▐▛▀▀▘    ▐▛▀▜▌▐▌ ▐▌  █  ▐▛▀▜▌  █
▝▚▄▞▘▐▙▄▄▖ █  ▗▄█▄▖▐▌  ▐▌▐▌ ▐▌ █  ▐▙▄▄▖    ▐▌ ▐▌▝▚▄▞▘  █  ▐▌ ▐▌ ▄▄▄▖
                                                              
                                                              
                                                                                                                                              
  \n
  `)
main().catch((err) => {
  console.error("Failed to sync API types:", err);
  process.exit(1);
});